<div class="btn-group">
    <a href="<?php echo $this->url(array('module'=>'facturacion','controller'=>'cliente'),'',true);?>"><button class="btn btn-primary"><i class="icon-folder-open icon-white"></i> Clientes</button></a>
    <a href="<?php echo $this->url(array('module'=>'facturacion','controller'=>'cliente'),'',true);?>"><button class="btn btn-primary"><i class="icon-arrow-up icon-white"></i> Facturas Emitidas</button></a>
    <a href="<?php echo $this->url(array('module'=>'facturacion','controller'=>'cliente'),'',true);?>"><button class="btn btn-primary"><i class="icon-arrow-down icon-white"></i> Facturas Recibidas</button><a/>
    <a href="<?php echo $this->url(array('module'=>'facturacion','controller'=>'cliente'),'',true);?>"><button class="btn btn-primary"><i class="icon-edit icon-white"></i> Notas de Crédito</button><a/>
</div>