<center>
    <br />
    <?php if(isset($this->error)) :?>
        <div class="alert alert-danger">  
            <a class="close" data-dismiss="alert" href="#">&times;</a>
            <h2>¡Error!</h2>
            <?php if($this->error == 1) :?>  
                El <strong>email</strong> no se encuentra registrado en el sistema
            <?php elseif($this->error == 2) :?>
                La <strong>contraseña</strong> no coincide con el email
            <?php elseif($this->error == 3) :?>
                No se puedo ejecutar la operación
            <?php endif;?>
        </div>
    <?php endif;?>
    <div class="page-header">
        <h1>GESTIÓN<small><br />Sistema de gestión interna de la empresa</small></h1>
    </div>
    <?php echo $this->login;?>
</center>