<div class="page-header">
    <h1>Sin permiso de acceso</h1><br />
    <div class="well well-small">
        <h2><small>1. Debes tener ingresar tu <strong>email</strong> y <strong>clave</strong> para ingresar al sistema.</small></h2>
        <h2><small>2. Si ya realizaste este paso anteriormente signifca que no tienes permiso de acceder a este modulo de la plataforma.</small></h2>
    </div>
    <a class="btn btn-primary btn-large" href="<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'index'),'',true);?>">¡ Quiero acceder !</a>
</div>
