<div class="page-header">
    <h1><?php echo $this->titulo;?><br /><small><?php echo $this->resumen;?></small></h1>
</div>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'tablero'),'',true);?>/">Inicio</a> <span class="divider">/</span></li>
    <li class="active">Hosting</li>
</ul>
<a href="<?php echo $this->url(array('module'=>'hosting','controller'=>'index','action'=>'agregar'),'',true);?>/" class="btn btn-success pull-right"><i class="icon-white icon-plus"></i> Agregar recordatorio</a>
<br /><br /> 
<?php if ($this->error) : ?>
    <div class="alert alert-error">
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <h2>¡ERROR!</h2> No fue posible ejecutar esta acción, intenta nuevamente.
    </div>   
<?php elseif ($this->exito) : ?>   
    <div class="alert alert-success">
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <h2>¡EXITO!</h2> Se ejecuto exitosamente esta acción.
    </div>        
<?php endif; ?>
<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>Cliente</th>
            <th>Dominio</th>
            <th>Email</th>
            <th>Cobro</th>
            <th></th>
        </tr>
    </thead>        
    <tbody>
        <?php if(count($this->datos)>0) :?>
        <?php foreach($this->datos as $retorno) :?>
            <tr>
                <td><?php echo $retorno->cliente;?></td>
                <td><?php echo $retorno->dominio;?></td>
                <td><?php echo $retorno->email;?></td>
                <td><?php echo $retorno->cobro;?></td>
                <td>
                    <div class="btn-group">
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">Acciones <span class="caret"></span></a>                    
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->url(array('module'=>'hosting','controller'=>'index','action'=>'editar','id'=>$retorno->id),'',true);?>"><i class="icon-pencil"></i> Editar</a></li>
                            <li><a href="<?php echo $this->url(array('module'=>'hosting','controller'=>'index','action'=>'eliminar','id'=>$retorno->id),'',true);?>"><i class="icon-trash"></i> Eliminar</a></li>
                        </ul>                    
                    </div>
                </td>
            </tr>
        <?php endforeach;?>
        <?php endif;?>
    </tbody>
</table>