<div class="page-header">
    <h1><?php echo $this->titulo;?><br /><small><?php echo $this->resumen;?></small></h1>
</div>
<ul class="thumbnails">
    <li class="span4">
        <div class="thumbnail centro">
            <img src="http://placehold.it/260x180" alt="">
            <h5 class="abajo masgrande"><i class="icon-folder-close"></i> MÓDULO OTI's</h5>
            <p class="gris">Control de trabajos internos de la empresa</p>
            <p><a href="#" class="btn btn-primary btn-large"><i class="icon-ok icon-white"></i> INGRESAR</a></p>
        </div>
    </li>
    <li class="span4">
        <div class="thumbnail centro">
            <img src="http://placehold.it/260x180" alt="">
            <h5 class="abajo masgrande"><i class="icon-folder-close"></i> MÓDULO FACTURACION</h5>
            <p class="gris">Control de trabajos internos de la empresa</p>
            <p><a href="#" class="btn btn-primary btn-large"><i class="icon-ok icon-white"></i> INGRESAR</a></p>
        </div>
    </li>
    <li class="span4">
        <div class="thumbnail centro">
            <img src="http://placehold.it/260x180" alt="">
            <h5 class="abajo masgrande"><i class="icon-folder-close"></i> MÓDULO SOTA</h5>
            <p class="gris">Control de trabajos internos de la empresa</p>
            <p><a href="#" class="btn btn-primary btn-large"><i class="icon-ok icon-white"></i> INGRESAR</a></p>
        </div>
    </li>
    <li class="span4">
        <div class="thumbnail centro">
            <img src="http://placehold.it/260x180" alt="">
            <h5 class="abajo masgrande"><i class="icon-folder-close"></i> MÓDULO HOSTING</h5>
            <p class="gris">Control clientes con cuenta hosting</p>
            <p><a href="<?php echo $this->url(array('module'=>'hosting','controller'=>'index','action'=>'index'),'',true);?>" class="btn btn-primary btn-large"><i class="icon-ok icon-white"></i> INGRESAR</a></p>
        </div>
    </li>    
</ul>