<?php echo $this->doctype();echo "\n"; ?>
<html>
<head>   
<?php echo $this->headTitle();echo "\n"; ?>
<?php echo $this->headMeta();echo "\n"; ?>
<?php echo $this->headLink();echo "\n"; ?>
<?php echo $this->headScript();echo "\n"; ?>  
</head>
<body>
    <div class="container">
        <?php echo $this->action('top','layout','default');?>   
        <?php echo $this->layout()->content; ?>
        <?php echo $this->action('footer','layout','default');?>   
    </div>
</body>
</html>