<div class="page-header">
    <h1><?php echo $this->titulo;?><br /><small><?php echo $this->resumen;?></small></h1>
</div>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'tablero'),'',true);?>/">Inicio</a> <span class="divider">/</span></li>
    <li class="active">Subareas</li>
</ul>
<a href="<?php echo $this->url(array('module'=>'mantenedor','controller'=>'subarea','action'=>'agregar'),'',true);?>/" class="btn btn-success pull-right"><i class="icon-white icon-plus"></i> Agregar subarea</a>
<br /><br /> 
<?php if ($this->error) : ?>
    <div class="alert alert-error">
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <h2>¡ERROR!</h2> No fue posible ejecutar esta acción, intenta nuevamente.
    </div>   
<?php elseif ($this->exito) : ?>   
    <div class="alert alert-success">
        <a class="close" data-dismiss="alert" href="#">&times;</a>
        <h2>¡EXITO!</h2> Se ejecuto exitosamente esta acción.
    </div>        
<?php endif; ?>
<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Nombre área</th>
            <th width="90"></th>
        </tr>
    </thead>      
    <tbody>
        <?php foreach($this->datos as $retorno) :?>
        <tr>
            <td><?php echo $retorno->nombre_subarea;?></td>
            <td><?php echo $retorno->nombre_area;?></td>
            <td>
                <div class="btn-group">
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">Acciones <span class="caret"></span></a>                    
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url(array('module'=>'mantenedor','controller'=>'subarea','action'=>'editar','id'=>$retorno->id_subarea),'',true);?>"><i class="icon-pencil"></i> Editar</a></li>
                        <li><a href="<?php echo $this->url(array('module'=>'mantenedor','controller'=>'subarea','action'=>'eliminar','id'=>$retorno->id_subarea),'',true);?>"><i class="icon-trash"></i> Eliminar</a></li>
                    </ul>                    
                </div>            
            </td>
        </tr>
        <?php endforeach; unset($retorno);?>
    </tbody>
</table>    