<div class="page-header">
    <h1><?php echo $this->titulo;?><br /><small><?php echo $this->resumen;?></small></h1>
</div>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array('module'=>'default','controller'=>'tablero'),'',true);?>/">Inicio</a> <span class="divider">/</span></li>
    <li><a href="<?php echo $this->url(array('module'=>'mantenedor','controller'=>'tipocliente'),'',true);?>/">Tipo Cliente</a> <span class="divider">/</span></li>
    <li class="active">Agregar Tipo Cliente</li>
</ul>
<div class="well">
    <h3>COMPLETA EL FORMULARIO</h3>    
    <?php echo $this->formulario;?>
</div>